# Generated by Django 3.2.13 on 2022-06-15 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ouvrant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeUser', models.CharField(choices=[('Distributeur', 'Distributeur'), ('MDM', 'MDM')], default='dis', max_length=13)),
                ('niveau', models.CharField(choices=[('ad', 'Admin'), ('res_region', 'Responsable_region'), ('res_dis', 'Responsable_distributeur'), ('dis', 'Distributeur')], default='dis', max_length=30)),
                ('num', models.CharField(blank=True, max_length=100, null=True)),
                ('addresse', models.CharField(blank=True, max_length=300, null=True)),
                ('tir_id_wave', models.CharField(blank=True, max_length=20, null=True)),
                ('first_login', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShowroomDepot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=120)),
                ('num', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('addresse', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('show', 'Showroom'), ('dep', 'Depot')], default='show', max_length=4)),
                ('active', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('O', 'Ouvrant'), ('C', 'Cadre'), ('E', 'Embrochure'), ('S', 'Serrure'), ('G', 'Grille')], default='O', max_length=1)),
                ('action', models.CharField(choices=[('E', 'Entree'), ('S', 'Sortie')], default='E', max_length=1)),
                ('quantite', models.IntegerField()),
                ('typePorte', models.CharField(choices=[('PP', 'Porte de passage'), ('PDV', 'Porte double vantaux'), ('PEM', "Porte d'entrée massive"), ('PTEC', 'Technique'), ('PCF30', 'Porte coupe-Feu 30mm'), ('PCF45', 'Porte coupe-Feu 45mm'), ('PCF60', 'Porte coupe-Feu 60mm')], default='pp', max_length=7)),
                ('modelePorte', models.CharField(choices=[('STAR', 'Star Massif'), ('2F', '2F'), ('4F', '4F'), ('6F', '6F'), ('4FL', '4FL'), ('EL1', 'EL1'), ('EL7', 'EL7'), ('Spéciale', 'Spéciale')], default='STAR', max_length=8)),
                ('couleur', models.CharField(choices=[('FCH', 'Chêne'), ('FAC', 'Acajou'), ('FJP', 'Joplin'), ('FWE', 'Wengue'), ('BL', 'Blanc')], default='FCH', max_length=5)),
                ('nombreVentaux', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1)),
                ('largeurPrecadre', models.CharField(blank=True, max_length=10, null=True)),
                ('hauteur', models.CharField(blank=True, max_length=10, null=True)),
                ('hauteurSup', models.CharField(blank=True, max_length=10, null=True)),
                ('largeur1o', models.CharField(blank=True, max_length=10, null=True)),
                ('largeur10sup', models.CharField(blank=True, max_length=10, null=True)),
                ('mecaSerrure', models.CharField(choices=[('SM', 'Sans mécanisation'), ('GC', 'Grande clé'), ('PC', 'Petite clé'), ('G', 'à gache'), ('C', 'Condamnation'), ('FELSI', '1 Point Sécurité'), ('FELDE', '3 Point Sécurité'), ('AP', 'Anti-Panique'), ('SCF', 'SERRURE COUPE FEU'), ('SCFDV', 'SERRURE COUPE FEU  DOUBLE VANTAUX')], default='GC', max_length=6)),
                ('serrure', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Oui', max_length=3)),
                ('protecteur', models.CharField(choices=[('P1F', '1Face'), ('P2F', '2Faces'), ('SP', 'Sans protecteur')], default='P1F', max_length=4)),
                ('sens', models.CharField(choices=[('D', 'Droite'), ('G', 'Gauche'), ('SS', 'Sans sens')], default='D', max_length=2)),
                ('vitrage', models.CharField(choices=[('SV', 'Sans vitre'), ('VB', 'Vitrage Bas'), ('VC', 'Vitrage Coté'), ('VH', 'Vitrage Haut'), ('VO', 'Vitrage Oculus')], default='SV', max_length=4)),
                ('grille', models.CharField(choices=[('GA', "Mecanisation de grille et grille d'Airation"), ('GSA', "Mécanisation De Grille Sans grille d'Airation"), ('SM', 'Sans Mécanisation')], default='GA', max_length=4)),
                ('quincaillerie', models.CharField(choices=[('N', 'Niquel'), ('SQ', 'Sans quincaillerie')], default='GA', max_length=4)),
                ('epaisseurMur', models.CharField(blank=True, max_length=10, null=True)),
                ('epaisseurMurSup', models.CharField(blank=True, max_length=10, null=True)),
                ('cadreUtilise', models.CharField(blank=True, max_length=10, null=True)),
                ('embrochure', models.CharField(blank=True, max_length=10, null=True)),
                ('couvreJointHauteur', models.CharField(blank=True, max_length=10, null=True)),
                ('couvreJointLargeur', models.CharField(blank=True, max_length=10, null=True)),
                ('coupeCouvreJoint', models.CharField(blank=True, max_length=10, null=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.showroomdepot')),
            ],
        ),
        migrations.CreateModel(
            name='ShowroomDepotRel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Depot', to='Login.showroomdepot')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Showroom', to='Login.showroomdepot')),
            ],
        ),
        migrations.AddField(
            model_name='showroomdepot',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.ville'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.ville'),
        ),
        migrations.CreateModel(
            name='DistributeurPot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=120)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('num', models.CharField(blank=True, max_length=100, null=True)),
                ('addresse', models.CharField(blank=True, max_length=300, null=True)),
                ('niveau', models.CharField(choices=[('ad', 'Admin'), ('res_region', 'Responsable_region'), ('res_dis', 'Responsable_distributeur'), ('dis', 'Distributeur')], default='dis', max_length=30)),
                ('tir_id_wave', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=False)),
                ('vue', models.BooleanField(default=False)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.distributeurpot')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.ville')),
            ],
        ),
    ]
